// let course = "TypeScript";
// let duration = 30;
// console.log(course, duration);
// let total = 100;
// total = "200";
// console.log(total + 50);   
var number = 100;
console.log(number);
value = 200;
console.log(value);
